language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  - platformio lib install 883

script:
  - platformio run -e bluepill -e uno
